apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fuchicorp-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod

spec:
  rules:
  - host: vault.{{ .Values.domain_name}}
    http:
      paths:
      - backend:
          serviceName: vault-service
          servicePort: {{ .Values.vaultport }}
  tls:
  - hosts:
    - vault.{{ .Values.domain_name}}
    secretName: tls-prod-cert
