apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexus.fullname" . }}
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port-docker }}
      targetPort: {{ .Values.service.targetport-docker }}
      protocol: TCP
      name: docker
    - port: {{ .Values.service.port-nexus }}
      targetPort: {{ .Values.service.targetport-nexus }}
      protocol: TCP
      name: nexus
  selector:
    {{- include "nexus.selectorLabels" . | nindent 4 }}
